#+STARTUP: show2levels
* Freebsd nixpkgs
** Project overview

Nixpkgs Podman containers on Freebsd with home-manager and flakes

🎥 [[https://youtu.be/kbz-wWjVJ1I][Nixpkgs Podman containers on Freebsd with home-manager and flakes]]

This allows you to upgrade applications using home-manager
instead of destroying the container and rebuilding it.

Development environment with flakes for use with nix-develop

Run Linux command line and gui applications on FreeBSD with full Nvidia Cuda hardware acceleration.

Mounts the Linuxulator libraries from Freebsd into the Podman containers,
so you dont need to install the Nvidia driver into the container.

Wayland/X11 and PulseAudio Pass-through.

Displays graphics and routes audio via native FreeBSD sockets mounted inside the Podman container.

Hardware accelerated video.

Persistent storage for files so settings are retained when stopping containers.

Directory mounted from Freebsd into the Podman container for file access.

GUI Applications launched with desktop entries on Freebsd.

*** Pre-configured Applications
**** Browsers
***** Firefox with hardware accelerated video and Widevine DRM support.

[[https://www.firefox.com/en-GB/]]

***** Tor Browser

[[https://www.torproject.org/download/]]

**** Development
***** C

[[https://en.cppreference.com/c]]

***** ffmpeg

[[https://www.ffmpeg.org/]]

***** Latex

[[https://www.tug.org/]]

***** Rust

[[https://rust-lang.org/]]

**** irc
***** Konversation

[[https://konversation.kde.org/]]

**** Video
***** Handbrake

[[https://handbrake.fr/]]

**** Web
***** Searxng

[[https://docs.searxng.org/]]

** Initial set up
*** Follow the podman install instructions

Follow the podman install instruction to get podman working.

Once you have the hello world container working you can proceed with the installation.

*** Clone the git repository

The podman set up instructions will set up a zfs dataset which is mounted at ~/podman.

Change into the podman directory.

#+begin_src sh
cd ~/podman
#+end_src

Clone the git repository.

#+begin_src sh
git clone https://github.com/NapoleonWils0n/freebsd-nixpkgs.git
#+end_src

*** Required packages for audio

You need pipewire, pulseaudio and pavucontrol installed.

#+begin_src sh
doas pkg install pipewire pulseaudio pavucontrol
#+end_src

*** Pulseaudio config
**** Option one use the Makefile

#+begin_src sh
cd ~/podman/freebsd-nixpkgs/assets/pulseaudio
#+end_src

run the Makefile to create the directory and file.

#+begin_src sh
make
#+end_src

**** Option two manually create the directory and file

Create the pulseaudio directory.

#+begin_src sh
mkdir -p ~/.config/pulse
#+end_src

Create the default.pa file.

#+begin_src sh
vi ~/.config/pulse/default.pa
#+end_src

Add the following code.

#+begin_src conf
#!/usr/local/bin/pulseaudio -nF

# include default.pa and override
.include /usr/local/etc/pulse/default.pa

# pulseaudio.socket
.ifexists module-esound-protocol-unix.so
load-module module-esound-protocol-unix
.endif
load-module module-native-protocol-unix socket=/tmp/pulseaudio.socket
#+end_src

*** wrapper-freebsd-nix

The wrapper-freebsd-nix script is used to launch gui applications and works with the wrapper-podman script which is installed in the podman containers and a desktop entry.

Copy the wrapper-freebsd-nix script to your bin directory.

If you have a bin directory in your home.

#+begin_src sh
cp ~/podman/freebsd-nixpkgs/assets/scripts/wrappers/wrapper-freebsd-nix ~/bin
#+end_src

If you dont have a bin directory in your home you can copy the script to.

#+begin_example
/usr/local/bin
#+end_example

#+begin_src sh
doas cp ~/podman/freebsd-nixpkgs/assets/scripts/wrappers/wrapper-freebsd-nix /usr/local/bin
#+end_src

** Build the images
*** Home Manager 

After building, starting and entering a container use the following commands to bootstrap home-manager,
install and update applications.

**** Home-manager install

Bootstrap Home Manager, build and install applications.

#+begin_src sh
nix run github:nix-community/home-manager -- switch --flake ~/.config/home-manager
#+end_src

**** Update flake dependencies

Update all input dependencies declared in your flake configuration and refresh the flake.lock file:

#+begin_src sh
nix flake update --flake ~/.config/home-manager
#+end_src

**** Update applications installed with home-manager.

Apply local configuration changes or rebuild the environment after updating flake inputs:

#+begin_src sh
home-manager switch --flake ~/.config/home-manager
#+end_src

**** Garbage collection
***** list generations

#+begin_src sh
nix-env --list-generations
#+end_src

***** delete generations

keep the current generation and the 5 previous generations

#+begin_src sh
nix-env --delete-generations +6
#+end_src

***** nix-store gc

run garbage collection on the nix-store

#+begin_src sh
nix-store --gc
#+end_src

*** Browsers
**** Firefox
***** Resources

[[https://www.firefox.com/]]

***** Change directory into the firefox directory

#+begin_src sh
cd ~/podman/freebsd-nixpkgs/containers/browsers/firefox
#+end_src

***** Run the Makefile

Run make Makefile which will create the persistent storage directories.

And the .env file which will set your username, id and set the mounted Downloads directory.

Make sure to review the .env file to make sure everything is correct.

#+begin_src sh
make
#+end_src

***** Build the container

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_UID="$(id -u)" \
--build-arg HOST_USER="${USER}" \
-t localhost/firefox-nix .
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** Enter container

#+begin_src sh
doas podman exec -it -u ${USER} -e USER=${USER} firefox-nix /bin/sh -l
#+end_src

***** home-manager install and switch

#+begin_src sh
nix run github:nix-community/home-manager -- switch --flake ~/.config/home-manager
#+end_src

***** flake update

#+begin_src sh
nix flake update --flake ~/.config/home-manager
#+end_src

***** home-manager switch

#+begin_src sh
home-manager switch --flake ~/.config/home-manager
#+end_src

***** stop the container

When you have finished you can exit the container.

#+begin_src sh
exit
#+end_src

And then stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

***** firefox-nix.desktop

Copy the firefox-nix.desktop file into

#+begin_example
~/.local/share/applications
#+end_example

#+begin_src sh
cp ~/podman/freebsd-nixpkgs/assets/applications/browsers/firefox/firefox-nix.desktop ~/.local/share/applications
#+end_src

Copy the desktop icon into place

#+begin_src sh
doas cp ~/podman/freebsd-nixpkgs/assets/applications/browsers/firefox/icon/firefox.png /usr/local/share/icons/hicolor/scalable/apps/
#+end_src

**** Tor Browser
***** Resources

[[https://www.torproject.org/download/]]

***** Change directory into the Tor Browser directory

#+begin_src sh
cd ~/podman/freebsd-nixpkgs/containers/browsers/tor-browser
#+end_src

***** Run the Makefile

Run make Makefile which will create the persistent storage directories.

And the .env file which will set your username, id and set the mounted Downloads directory.

Make sure to review the .env file to make sure everything is correct.

#+begin_src sh
make
#+end_src

***** Build the container

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_UID="$(id -u)" \
--build-arg HOST_USER="${USER}" \
-t localhost/tor-browser-nix .
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** Enter container

#+begin_src sh
doas podman exec -it -u ${USER} -e USER=${USER} tor-browser-nix /bin/sh -l
#+end_src

***** home-manager install and switch

#+begin_src sh
nix run github:nix-community/home-manager -- switch --flake ~/.config/home-manager
#+end_src

***** flake update

#+begin_src sh
nix flake update --flake ~/.config/home-manager
#+end_src

***** home-manager switch

#+begin_src sh
home-manager switch --flake ~/.config/home-manager
#+end_src

***** stop the container

When you have finished you can exit the container.

#+begin_src sh
exit
#+end_src

And then stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

***** tor-browser-nix.desktop

Copy the tor-browser.desktop file into

#+begin_example
~/.local/share/applications
#+end_example

#+begin_src sh
cp ~/podman/freebsd-nixpkgs/assets/applications/browsers/tor-browser/tor-browser-nix.desktop ~/.local/share/applications
#+end_src

Copy the desktop icon into place

#+begin_src sh
doas cp ~/podman/freebsd-nixpkgs/assets/applications/browsers/tor-browser/icon/tor-browser.png /usr/local/share/icons/hicolor/scalable/apps/
#+end_src

*** Development
**** flakes-nix
***** Change directory 

#+begin_src sh
cd ~/podman/freebsd-nixpkgs/containers/development/flakes-nix
#+end_src

***** Run the Makefile

#+begin_src sh
make
#+end_src

***** Build the container

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_UID="$(id -u)" \
--build-arg HOST_USER="${USER}" \
-t localhost/flakes-nix .
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** Enter container

#+begin_src sh
doas podman exec -it -u ${USER} -e USER=${USER} flakes-nix /bin/sh -l
#+end_src

***** home-manager install and switch

#+begin_src sh
nix run github:nix-community/home-manager -- switch --flake ~/.config/home-manager
#+end_src

***** flakes
****** c

change into the c directory

#+begin_src sh
cd flakes/c
#+end_src

run nix develop

#+begin_src sh
nix develop
#+end_src

****** ffmpeg

change into the ffmpeg directory

#+begin_src sh
cd flakes/ffmpeg
#+end_src

run nix develop

#+begin_src sh
nix develop
#+end_src

****** latex

change into the latex directory

#+begin_src sh
cd flakes/latex
#+end_src

run nix develop

#+begin_src sh
nix develop
#+end_src

****** rust

change into the rust directory

#+begin_src sh
cd flakes/rust
#+end_src

run nix develop

#+begin_src sh
nix develop
#+end_src

******* change into the workspace directory

#+begin_src sh
cd ../../workspace
#+end_src

******* create a directory for your project 

#+begin_src sh
mkdir -p rust
#+end_src

******* change into the directory

#+begin_src sh
cd rust
#+end_src

******* cargo init

#+begin_src sh
cargo init
#+end_src

******* cargo run

#+begin_src sh
cargo run
#+end_src

******* nix build

build for nix

#+begin_src sh
nix build
#+end_src

******* linux build

#+begin_src sh
cargo build --release --target x86_64-unknown-linux-musl
#+end_src

The binaries will be located in target/x86_64-unknown-linux-musl/release/.

list the binaries

#+begin_src sh
ls -l target/x86_64-unknown-linux-musl/release/
#+end_src

How to verify they are truly "Static"
One of the main reasons to use musl is to ensure the binary has no external dependencies.

You can verify this by running the ldd command on one of the new binaries:

#+begin_src sh
ldd target/x86_64-unknown-linux-musl/release/scene-detect-auto
#+end_src

Expected Output: It should say statically linked or not a dynamic executable.

This confirms that a user on Ubuntu, Debian,
or Arch can just download that file and run it immediately (provided they have ffmpeg installed).

Copy the binaries to the build directory on the desktop

#+begin_src sh
fd -t f -d 1 -E "*.*" . target/x86_64-unknown-linux-musl/release/ -x cp {} ~/Desktop/build/linux/
#+end_src

******* Windows build

To build binaries for Windows, we use the MinGW-w64 toolchain.
You must be inside the nix develop shell to run this command.

This ensures the environment variables for the linker and library paths are correctly set.

#+begin_src sh
nix develop
#+end_src

Build the binaries using the gnu target

#+begin_src sh
cargo build --release --target x86_64-pc-windows-gnu
#+end_src

The binaries will be located in target/x86_64-pc-windows-gnu/release/.

list the binaries

#+begin_src sh
ls -l target/x86_64-pc-windows-gnu/release/*.exe 
#+end_src

Copy the binaries to the build directory on the desktop

#+begin_src sh
fd -t f -e exe --max-depth 1 . target/x86_64-pc-windows-gnu/release/ -x cp {} ~/Desktop/build/windows/
#+end_src

******* cargo clean

#+begin_src sh
cargo clean
#+end_src

***** flake update

#+begin_src sh
nix flake update --flake ~/.config/home-manager
#+end_src

***** home-manager switch

#+begin_src sh
home-manager switch --flake ~/.config/home-manager
#+end_src

***** stop the container

When you have finished you can exit the container.

#+begin_src sh
exit
#+end_src

And then stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

*** irc
**** Konversation
***** Resources

[[https://konversation.kde.org/]]

***** Change directory into the konversation directory

#+begin_src sh
cd ~/podman/freebsd-nixpkgs/containers/irc/konversation
#+end_src

***** Run the Makefile

Run make Makefile which will create the persistent storage directories.

And the .env file which will set your username, id and set the mounted Downloads directory.

Make sure to review the .env file to make sure everything is correct.

#+begin_src sh
make
#+end_src

***** Build the container

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_UID="$(id -u)" \
--build-arg HOST_USER="${USER}" \
-t localhost/konversation-nix .
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** Enter container

#+begin_src sh
doas podman exec -it -u ${USER} -e USER=${USER} konversation-nix /bin/sh -l
#+end_src

***** home-manager install and switch

#+begin_src sh
nix run github:nix-community/home-manager -- switch --flake ~/.config/home-manager
#+end_src

***** flake update

#+begin_src sh
nix flake update --flake ~/.config/home-manager
#+end_src

***** home-manager switch

#+begin_src sh
home-manager switch --flake ~/.config/home-manager
#+end_src

***** exit the container

When you have finished you can exit the container.

#+begin_src sh
exit
#+end_src

And then stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

***** konversation-nix.desktop

Copy the konversation-nix.desktop file into

#+begin_example
~/.local/share/applications
#+end_example

#+begin_src sh
cp ~/podman/freebsd-nixpkgs/assets/applications/irc/konversation/konversation-nix.desktop ~/.local/share/applications
#+end_src

Copy the desktop icon into place

#+begin_src sh
doas cp ~/podman/freebsd-nixpkgs/assets/applications/irc/konversation/icon/konversation.png /usr/local/share/icons/hicolor/scalable/apps/
#+end_src

*** Translation
***** Resources

[[https://github.com/XapaJIaMnu/translatelocally]]

***** Change directory into the konversation directory

#+begin_src sh
cd ~/podman/freebsd-nixpkgs/containers/translation/translatelocally
#+end_src

***** Run the Makefile

Run make Makefile which will create the persistent storage directories.

And the .env file which will set your username, id and set the mounted Downloads directory.

Make sure to review the .env file to make sure everything is correct.

#+begin_src sh
make
#+end_src

***** Build the container

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_UID="$(id -u)" \
--build-arg HOST_USER="${USER}" \
-t localhost/translatelocally-nix .
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** Enter container

#+begin_src sh
doas podman exec -it -u ${USER} -e USER=${USER} translatelocally-nix /bin/sh -l
#+end_src

***** home-manager install and switch

#+begin_src sh
nix run github:nix-community/home-manager -- switch --flake ~/.config/home-manager
#+end_src

***** flake update

#+begin_src sh
nix flake update --flake ~/.config/home-manager
#+end_src

***** home-manager switch

#+begin_src sh
home-manager switch --flake ~/.config/home-manager
#+end_src

***** exit the container

When you have finished you can exit the container.

#+begin_src sh
exit
#+end_src

And then stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

***** translatelocally-nix.desktop

Copy the konversation-nix.desktop file into

#+begin_example
~/.local/share/applications
#+end_example

#+begin_src sh
cp ~/podman/freebsd-nixpkgs/assets/applications/translation/translatelocally/desktop-entry/translatelocally.desktop ~/.local/share/applications
#+end_src

*** Video
**** Handbrake
***** Resources

[[https://github.com/handbrake/handbrake]]

***** Change directory into the handbrake directory

#+begin_src sh
cd ~/podman/freebsd-nixpkgs/containers/video/handbrake
#+end_src

***** Run the Makefile

Run make Makefile which will create the persistent storage directories.

And the .env file which will set your username, id and set the mounted Downloads directory.

Make sure to review the .env file to make sure everything is correct.

#+begin_src sh
make
#+end_src

***** Build the container

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_UID="$(id -u)" \
--build-arg HOST_USER="${USER}" \
-t localhost/handbrake-nix .
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** Enter container

#+begin_src sh
doas podman exec -it -u ${USER} -e USER=${USER} handbrake-nix /bin/sh -l
#+end_src

***** home-manager install and switch

#+begin_src sh
nix run github:nix-community/home-manager -- switch --flake ~/.config/home-manager
#+end_src

***** flake update

#+begin_src sh
nix flake update --flake ~/.config/home-manager
#+end_src

***** home-manager switch

#+begin_src sh
home-manager switch --flake ~/.config/home-manager
#+end_src

***** exit the container

When you have finished you can exit the container.

#+begin_src sh
exit
#+end_src

And then stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

***** handbrake-nix.desktop

Copy the handbrake-nix.desktop file into

#+begin_example
~/.local/share/applications
#+end_example

#+begin_src sh
cp ~/podman/freebsd-nixpkgs/assets/applications/video/handbrake/handbrake-nix.desktop ~/.local/share/applications
#+end_src

Copy the desktop icon into place

#+begin_src sh
doas cp ~/podman/freebsd-nixpkgs/assets/applications/video/handbrake/icon/fr.handbrake.ghb.png /usr/local/share/icons/hicolor/scalable/apps/
#+end_src

*** Web
**** searxng
***** Resources

[[https://github.com/searxng/searxng]]

[[https://docs.searxng.org/]]

***** Change directory 

#+begin_src sh
cd ~/podman/freebsd-nixpkgs/containers/web/searxng
#+end_src

***** Run the Makefile

#+begin_src sh
make
#+end_src

***** Build the container

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_UID="$(id -u)" \
--build-arg HOST_USER="${USER}" \
-t localhost/searxng-nix .
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** Enter container

#+begin_src sh
doas podman exec -it -u ${USER} -e USER=${USER} searxng-nix /bin/sh -l
#+end_src

***** home-manager install and switch

#+begin_src sh
nix run github:nix-community/home-manager -- switch --flake ~/.config/home-manager
#+end_src

***** flake update

#+begin_src sh
nix flake update --flake ~/.config/home-manager
#+end_src

***** home-manager switch

#+begin_src sh
home-manager switch --flake ~/.config/home-manager
#+end_src

***** exit the container

When you have finished you can exit the container.

#+begin_src sh
exit
#+end_src

And then stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

***** Makefile

The searxng container has a Makefile to make it easy to stop and start the container

Create a directory for Makefiles

#+begin_src sh
mkdir -p ~/make
#+end_src

Copy the searxng directory to the make directory

#+begin_src sh
cp -r ~/podman/freebsd-nixpkgs/assets/makefiles/searxng ~/make
#+end_src

Change into the make searxng directory

#+begin_src sh
cd ~/make/searxng
#+end_src

Start searxng

#+begin_src sh
make
#+end_src

Stop searxng

#+begin_src sh
make clean
#+end_src

*** Custom containers

You can create a custom directory for your own containers.

Which wont be tracked by git,
because i have set that directory to be ignored using gitignore.

#+begin_src sh
mkdir -p ~/podman/freebsd-nixpkgs/containers/custom
#+end_src

Then create the project in the custom directory.

#+begin_src sh
mkdir -p ~/podman/freebsd-nixpkgs/containers/custom/myproject
#+end_src

And copy the Dockerfile, compose.yaml, .env and the Makefile from one of the other projects.

*** Prune old images

#+begin_src sh
doas podman image prune -f
#+end_src

**** Delete the firefox container

#+begin_src sh
doas podman rmi localhost/firefox-nix:latest
#+end_src

**** Delete the flakes container

#+begin_src sh
doas podman rmi localhost/flakes-nix:latest
#+end_src

**** Delete the handbrake container

#+begin_src sh
doas podman rmi localhost/handbrake-nix:latest
#+end_src

**** Delete the konversation container

#+begin_src sh
doas podman rmi localhost/konversation-nix:latest
#+end_src

**** Delete the searxng container

#+begin_src sh
doas podman rmi localhost/searxng-nix:latest
#+end_src

** Podman install

There's also a podman-suite meta package that will pull additional packages for you (buildah, skopeo).

To install podman-compose you need to install the py311-podman-compose package as well

#+begin_src sh
doas pkg install podman-suite py311-podman-compose
#+end_src

*** fstab

To properly support Podman's container restart policy, conmon needs fdescfs(5) to be mounted on /dev/fd.

If /dev/fd is not already mounted:

#+begin_src sh
doas mount -t fdescfs fdesc /dev/fd
#+end_src

To make it permanent, add the following line to /etc/fstab:

#+begin_src sh
doas vi /etc/fstab
#+end_src

#+begin_src conf
fdesc   /dev/fd         fdescfs         rw      0       0
#+end_src

#+begin_src sh
doas mount -t procfs proc /proc
#+end_src

*** linux

Enable Linux compatibility at boot

#+begin_src sh
doas sysrc linux_enable="YES"
#+end_src

Start the service and load the 64-bit Linux kernel module

#+begin_src sh
doas service linux start
#+end_src

Load linux 

#+begin_src sh
doas kldload linux64
#+end_src

Ensure it loads every boot

#+begin_src sh
doas sysrc kld_list+="linux64"
#+end_src

*** pf

#+begin_src sh
service pf enable
#+end_src

#+begin_src sh
service pf start
#+end_src

Note fix error

#+begin_src sh
doas sysrc 'pf_load=YES'
#+end_src

#+begin_src sh
kldload pf
#+end_src

Container networking relies on NAT to allow container network packets out to the host's network. This requires a PF firewall to perform the translation. A simple example is included - to use it:

#+begin_src sh
cp /usr/local/etc/containers/pf.conf.sample .
#+end_src

pf.conf.sample

#+begin_src conf
# Change these to the interface(s) with the default route
v4egress_if = "ix0"
v6egress_if = "ix0"

nat on $v4egress_if inet from <cni-nat> to any -> ($v4egress_if)
nat on $v6egress_if inet6 from <cni-nat> to !ff00::/8 -> ($v6egress_if)

rdr-anchor "cni-rdr/*"
nat-anchor "cni-rdr/*"
table <cni-nat>
#+end_src

Edit /etc/pf.conf and set v4egress_if, v6egress_if variables to your network interface(s)s

The sample PF configuration includes support for port redirections. These are implemented as redirect rules in anchors nested under cni-rdr.

Redirect rules will work if the destination address is localhost (e.g. 127.0.0.1 or ::1) - to enable this, the following line must be included in your /etc/pf.conf:

#+begin_src conf
nat-anchor "cni-rdr/*"
#+end_src

#+begin_src sh
doas vi /etc/pf.conf
#+end_src

#+begin_src conf
#=========================================================================#
# pf.conf
#=========================================================================#

#=========================================================================#
# variables, macro and tables                                             #
#=========================================================================#

int_if="lagg0" # lagg0 failover
v4egress_if = "lagg0" # podman
v6egress_if = "lagg0" # podman
vpn_if="tun0" # vpn interface
all_networks="0.0.0.0/0"
vpn_network="$vpn_if:network"
# 6881, 6882 = transmission. , 22000, 22000, 21027 = syncthing
# searxng podman = 8080
tcp_services = "{ ntp, 6881, 22000, 8080 }" # tcp services - torrent
udp_services = "{ ntp, 6882, 22000, 21027 }" # udp services - torrent
#nfs_services = "{ 2049 }" # 2049 = nfs
icmp_types = "{ echoreq, unreach }"
tcp_state="flags S/SA keep state"
udp_state="keep state"

#table <internet> { $all_networks, !self, !$int_if:network } # internet
table <lan> { $int_if:network, !self }                      # lan network
table <myself> { self }                                     # self
table <martians> { 0.0.0.0/8 10.0.0.0/8 127.0.0.0/8 169.254.0.0/16     \
	 	   172.16.0.0/12 192.0.0.0/24 192.0.2.0/24 224.0.0.0/3 \
	 	   192.168.0.0/16 198.18.0.0/15 198.51.100.0/24        \
	 	   203.0.113.0/24 }                         # broken networks

#=========================================================================#
# global policy                                                           #
#=========================================================================#

set block-policy drop
set loginterface $int_if
set fingerprints "/etc/pf.os"
set skip on { lo0, cni-podman0 }
scrub in all fragment reassemble no-df max-mss 1440
# nat jail
nat on $int_if from {lo1:network} to any -> ($int_if)
# podman nat
nat on $v4egress_if inet from <cni-nat> to any -> ($v4egress_if)
nat on $v6egress_if inet6 from <cni-nat> to !ff00::/8 -> ($v6egress_if)
# podman anchor
rdr-anchor "cni-rdr/*"
nat-anchor "cni-rdr/*"
table <cni-nat>
# antispoof
antispoof log quick for { lo $int_if } label "block_spoofing"


#=========================================================================#
# block                                                                   #
#=========================================================================#

block log all # block log all
block return out quick inet6 all tag IPV6 # block ipv6 
block in quick inet6 all tag IPV6 # block ipv6


#=========================================================================#
# anchors                                                                 #
#=========================================================================#

# openvpn - anchor
anchor "openvpn"

#=========================================================================#
# traffic tag                                                             #
#=========================================================================#

# icmp
pass inet proto icmp all icmp-type $icmp_types keep state tag ICMP

# Allow the tcp and udp services defined in the macros at the top of the file
pass in on $int_if inet proto tcp from any to ($int_if) port $tcp_services $tcp_state tag TCP_IN
pass in on $int_if inet proto udp from any to ($int_if) port $udp_services $udp_state tag UDP_IN

# outbound traffic
block out on $int_if all
pass out quick on $int_if all modulate state
#+end_src

restart pf

#+begin_src sh
doas service pf restart
#+end_src

*** zfs

create a zfs dataset for podman

#+begin_src sh
doas zfs create -o mountpoint=/var/db/containers zroot/containers
#+end_src

*** sysctl

apply net.pf.filter_local=1

#+begin_src sh
doas sysctl net.pf.filter_local=1
#+end_src

set net.pf.filter_local=1 permanently

#+begin_src sh
doas vi /etc/sysctl.conf
#+end_src

#+begin_src conf
#=========================================================================#
# podman
#=========================================================================#

net.pf.filter_local=1
#+end_src

*** podman enable

Podman can restart containers after a host is rebooted. To enable this, use:

#+begin_src sh
doas sysrc podman_enable=YES
#+end_src

or you can manually edit your /etc/rc.conf

#+begin_src sh
doas vi /etc/rc.conf
#+end_src

#+begin_src conf
#=========================================================================#
# podman
#=========================================================================#

podman_enable=YES
#+end_src

*** registries.conf

edit the registries.conf to define repos to podman

#+begin_src sh
doas vi /usr/local/etc/containers/registries.conf
#+end_src

append the following code

#+begin_src conf
unqualified-search-registries = ["docker.io", "quay.io", "ghcr.io"]

[[registry]]
location = "docker.io"

[[registry]]
location = "quay.io"

[[registry]]
location = "ghcr.io"
#+end_src

*** podman zfs dataset for config files

Its good practice to create a zfs dataset for the podman directory

note: change djwilcox to your username in the examples below

we will also create a zfs dataset for our podman config files

#+begin_src sh
doas zfs create zroot/home/djwilcox/podman
#+end_src

change the permissions

#+begin_src sh
doas chown -R djwilcox:djwilcox /home/djwilcox/podman
#+end_src

if you dont want to create a zfs dataset

you can just create a directory

#+begin_src sh
mkdir -p ~/podman
#+end_src

*** doas podman set up

set up doas so you can can run podman without being prompted for a password

#+begin_src sh
doas vi /usr/local/etc/doas.conf
#+end_src

change username to your username

#+begin_src conf
#=========================================================================#
# doas.conf
#=========================================================================#

#=========================================================================#
# permit user
#=========================================================================#

permit keepenv setenv { PATH } username


#=========================================================================#
# allow root to switch to our user
#=========================================================================#

permit nopass keepenv setenv { PATH } root as username


#=========================================================================#
# permit user - no pass
#=========================================================================#

permit nopass keepenv setenv { PATH } username


#=========================================================================#
# podman permit user - no pass
#=========================================================================#

permit nopass keepenv username cmd /usr/local/bin/podman


#=========================================================================#
# root as root
#=========================================================================#

permit nopass keepenv root as root
#+end_src

*** devfs.rules

Add the localrules to your rc.conf with sysrc

#+begin_src sh
doas sysrc devfs_system_ruleset="localrules"
#+end_src

Or you can manually edit your rc.conf

#+begin_src sh
doas vi /etc/rc.conf
#+end_src

add the following code

#+begin_src conf
devfs_system_ruleset="localrules"
#+end_src

Note: add devfs rules to config

Edit your devfs.rules

#+begin_src sh
doas vi /etc/devfs.rules
#+end_src

Add the following code

#+begin_src conf
[localrules=5]
add path 'da*' mode 0660 group operator
add path 'dri/*' mode 0660 group video
add path 'drm/*' mode 0660 group video
add path 'input/*' mode 0660 group video
add path 'input/event*' mode 0660 group video
add path 'nvidia*' mode 0660 group video

[devfsrules_jail=4]
add include $devfsrules_unhide_basic
add include $devfsrules_unhide_login
add path 'mixer*' unhide
add path 'dsp*' unhide
add path 'dri*' unhide
add path 'drm*' unhide
add path 'nvidia*' unhide
add path 'speaker*' unhide
#+end_src

*** podman test

run the hello world podman container

#+begin_src sh
doas podman run --rm docker.io/dougrabson/hello
#+end_src

