#===============================================================================
# FILE: compose.yaml
# Project: searxng-nix
#===============================================================================


#===============================================================================
# Services Configuration
#===============================================================================

services:
  nix:
    # Build using the local lightweight Dockerfile
    build:
      context: .

      # use networking from the freebsd host
      network: host

      # HOST_USER set from .env is your user on Freebsd
      args:
        - HOST_USER=${HOST_USER}
        - HOST_UID=${HOST_UID}

    # image name
    image: localhost/searxng-nix

    # platform linux
    platform: linux/amd64

    # container name
    container_name: searxng-nix

    # os linux
    os: linux

    # use networking from the freebsd host
    network_mode: host

    # stdin and tty
    stdin_open: true
    tty: true

    # SIGKILL so the container stops cleaning using: doas podman-compose down
    stop_signal: SIGKILL


#===============================================================================
# Volume Mounts (Host Bindings & Jail Sockets)
#===============================================================================

    volumes:

      #=========================================================================
      # Persistent Nix Store & State volume
      #=========================================================================

      # tmpfs
      - nix-shm:/dev/shm

      # nix store
      - nix-store:/nix


      #=========================================================================
      # AUTOMATED PERSISTENT APPLICATION CONFIG WORKSPACE
      #=========================================================================

      # config
      - ./dotfiles/config:/home/${HOST_USER}/.config:rw

      # cache
      - ./dotfiles/cache:/home/${HOST_USER}/.cache:rw

      # local
      - ./dotfiles/local:/home/${HOST_USER}/.local:rw


      #=========================================================================
      # Nix Configuration File
      #=========================================================================

      # Nix Flakes Cache (Overlays .cache/nix with a native container volume)
      - nix-cache:/home/${HOST_USER}/.cache/nix

      # nix.conf
      - ./dotfiles/config/nix:/etc/nix:ro

      #=========================================================================
      # App mounts
      #=========================================================================

      # bin directory mounted from host in .env file
      - ./${HOST_BIN}:/home/${HOST_USER}/${HOST_BIN}:ro


#===============================================================================
# Entrypoint & Shell Initialization
#===============================================================================

    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        #=======================================================================
        # Explicitly create the nested dconf directory structure first
        #=======================================================================

        # tmp directory
        mkdir -p /home/${HOST_USER}/tmp

        # local share
        mkdir -p /home/${HOST_USER}/.local/share

        # chmod the tmp directory
        chmod 755 /home/${HOST_USER}/tmp


        #=======================================================================
        # Ensure Nix cache volume is owned by non-root user
        #=======================================================================

        mkdir -p /home/${HOST_USER}/.cache/nix
        chown -R ${HOST_USER}:${HOST_USER} /home/${HOST_USER}/.cache/nix


        #=======================================================================
        # Append environment parameters into .bashrc to survive runuser switch
        #=======================================================================

        # nix daemon-socket
        mkdir -p /nix/var/nix/daemon-socket
        chown -R root:nix-users /nix/var/nix/daemon-socket
        chmod 775 /nix/var/nix/daemon-socket

        # start the nix-daemon
        nix-daemon --daemon &

        # Touch and set permission BEFORE appending
        touch /home/${HOST_USER}/.bashrc
        chmod 644 /home/${HOST_USER}/.bashrc

        {

          # set the TMPDIR to ~/tmp
          echo 'export TMPDIR=/home/'"${HOST_USER}"'/tmp'

          # export the xdg directories
          echo 'export XDG_CONFIG_HOME=/home/'"${HOST_USER}"'/.config'
          echo 'export XDG_CACHE_HOME=/home/'"${HOST_USER}"'/.cache'
          echo 'export XDG_DATA_HOME=/home/'"${HOST_USER}"'/.local/share'
          echo 'export XDG_DATA_DIRS="/home/'"${HOST_USER}"'/.local/state/nix/profiles/profile/share:$XDG_DATA_DIRS"'

          # LOCALE ENVIRONMENT
          echo 'export LANG='"${HOST_LANG}"''
          echo 'export LC_COLLATE=C'

          # user and home
          echo 'export NIX_REMOTE=daemon'
          echo 'export USER='"${HOST_USER}"''
          echo 'export HOME=/home/'"${HOST_USER}"''
          echo 'export PATH=/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/usr/local/bin:/home/'"${HOST_USER}"'/.local/state/nix/profiles/profile/bin:$PATH'

          # SearXNG Environment Overrides
          echo 'export SEARXNG_SETTINGS_PATH=/home/'"${HOST_USER}"'/.config/searxng/settings.yml'
          echo 'export SEARXNG_LIMITER=false'

          # nix dont manage shell
          echo 'if [ -f "/home/'"${HOST_USER}"'/.local/state/nix/profiles/profile/etc/profile.d/hm-session-vars.sh" ]; then'
          echo '    . "/home/'"${HOST_USER}"'/.local/state/nix/profiles/profile/etc/profile.d/hm-session-vars.sh"'
          echo 'fi'

        } > /home/${HOST_USER}/.bashrc

        # add bashrc to profile
        echo '[ -f ~/.bashrc ] && . ~/.bashrc' > /home/${HOST_USER}/.profile

        #=======================================================================
        # Switch from root to our user
        #=======================================================================

        # chmod the home directory
        chmod 755 /home
        chmod 755 /home/${HOST_USER}
        chmod 644 /home/${HOST_USER}/.bashrc
        chown -R ${HOST_USER}:${HOST_USER} /home/${HOST_USER}

        # exec /bin/sh
        exec /bin/sh


#===============================================================================
# Named Volumes Definition
#===============================================================================

volumes:

  #=========================================================================
  # Shared Memory Volume
  # Provides 1GB of tmpfs space 
  #=========================================================================

  nix-shm:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=1g,mode=1777"


  #=========================================================================
  # Persistent Nix store volume
  #=========================================================================

  nix-store:


  #=========================================================================
  # Dedicated volume for Nix Flakes SQLite evaluation & fetcher caches
  #=========================================================================

  nix-cache:

